AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Private template

Parameters:
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - hml
      - prd
  FunctionLambdaName:
    Description: Lambda Name
    Type: String
    Default: lambda-mtls-key
  SquadName:
    Description: Squad Name (TAG)
    Type: String
    Default: architecture
  AppName:
    Description: App Name (TAG)
    Type: String
    Default: lambda-mtls-key
  LambdaOtelLayerARN:
    Description: Lambda ARN Otel Layer
    Type: String
    Default: arn:aws:lambda:us-east-2:901920570463:layer:aws-otel-collector-amd64-ver-0-90-1:1
  HandlerName:
    Type: String
    Description: Handler Name (go=main, python=index.handler)
    Default: main
  Timeout:
    Type: Number
    Description: Timeout in seconds
    Default: 3
  S3BucketParam:
    Description: Bucket lambda source (.zip)
    Type: String 
    Default: eliezerraj-908671954593-artifacts
  S3KeyParam:
    Description: Folder bucket lambda source (.zip)
    Type: String 
    Default: lambda-mtls-key/main.zip

  ManagedPolicyParameterOne:
    Description: Managed policy ONE (opcional)
    Type: String 
    Default: arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
  ManagedPolicyParameterTwo:
    Description: Managed policy TWO (opcional)
    Type: String 
    Default: arn:aws:iam::aws:policy/AmazonS3FullAccess
  ManagedPolicyParameterThree:
    Description: Managed policy THREE (opcional)
    Type: String 
    Default: arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
  Runtime:
    Description: Runtime Environment name e.g nodejs, provided.al2023(go1.x), python3.9
    Type: String
    ConstraintDescription: must be a valid environment (go 1.x)
    Default: provided.al2023

  VPCSubnetA:
    Description: Lambda deploy SubNet A
    Type: String
    Default: subnet-0ca2d45be9d6ab5bc
  VPCSubnetB:
    Description: Lambda deploy SubNet B
    Type: String
    Default: subnet-0b2b57acbb1da0623
  VPCSubnetC:
    Description: Lambda deploy SubNet C
    Type: String
    Default: subnet-05d3e7f4611c12a23
  VPCSecurityGroup:
    Description: Lambda deploy Security Group
    Type: String
    Default: sg-071e23394778596b2

Conditions:
  IsManagedPolicyParameterOne:    !Not [!Equals [ !Ref ManagedPolicyParameterOne, "" ]]
  IsManagedPolicyParameterTwo:    !Not [!Equals [ !Ref ManagedPolicyParameterTwo, "" ]]
  IsManagedPolicyParameterThree:  !Not [!Equals [ !Ref ManagedPolicyParameterThree, "" ]]

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - !If [ IsManagedPolicyParameterOne, !Ref ManagedPolicyParameterOne, !Ref 'AWS::NoValue' ]
        - !If [ IsManagedPolicyParameterTwo, !Ref ManagedPolicyParameterTwo, !Ref 'AWS::NoValue' ]
        - !If [ IsManagedPolicyParameterThree, !Ref ManagedPolicyParameterThree, !Ref 'AWS::NoValue' ]
      Policies:
      - PolicyName: lambda_policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "s3:*"
            Resource: "*"
          - Effect: Allow
            Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            - "logs:PutLogEvents"
            Resource: "*"

  LambdaFunction: 
    Type: "AWS::Lambda::Function"
    Properties: 
      FunctionName: !Ref FunctionLambdaName
      Handler: !Ref HandlerName
      Timeout: !Ref Timeout
      Runtime: !Ref Runtime
      Layers:
        - !Ref LambdaOtelLayerARN
      Environment:
        Variables:
          APP_NAME: 'lambda-mtls-key'
          BUCKET_NAME_KEY: 'eliezerraj-908671954593-mtls-truststore'
          ENV: !Ref Env
          FILE_PATH: '/'
          FILE_KEY: 'crl_ca.pem'
          REGION: 'us-east-2'
          OTEL_EXPORTER_OTLP_ENDPOINT: 'localhost:4317'
          VERSION: '1.0'
      VpcConfig:
        SecurityGroupIds:
          - Ref: VPCSecurityGroup	
        SubnetIds:
          - Ref: VPCSubnetA
          - Ref: VPCSubnetB
          - Ref: VPCSubnetC
      Role: 
        Fn::GetAtt: 
          - "LambdaExecutionRole"
          - "Arn"
      Code: 
        S3Bucket: !Ref S3BucketParam
        S3Key: !Ref S3KeyParam
      Tags:
      - Key: name
        Value: !Ref FunctionLambdaName
      - Key: squad
        Value: !Ref SquadName
      - Key: app
        Value: !Ref AppName

  LambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: LambdaFunction
    Properties:
      RetentionInDays: 7
      LogGroupName: !Join
        - ""
        - -  "/aws/lambda/"
          - !Ref LambdaFunction

  VersionLambda:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LambdaFunction
      Description: version Live

  AliasLambda:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref LambdaFunction
      FunctionVersion: !GetAtt VersionLambda.Version
      Name: LIVE

Outputs:
  LambdaFunctionARN:
    Value: !GetAtt 'LambdaFunction.Arn'